---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:

  selector:
    matchLabels:
      app: todo-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
#          image: todo-frontend:v1.0.0
          image: hub.comcast.net/sandbox/todo-frontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_URL
              value: "http://todo-api:8080"
