---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: todo-api
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      interval: 30s
      path: /actuator/prometheus
